export interface settingsType {
  _id: string
  radarr_URL: string
  radarr_KEY: string
  radarr_API_version: string
  radarr_active: boolean
  sonarr_URL: string
  sonarr_KEY: string
  sonarr_API_version: string
  sonarr_active: boolean
  lidarr_URL: string
  lidarr_KEY: string
  lidarr_API_version: string
  lidarr_active: boolean
  import_blocked: boolean
  wanted_missing: boolean
  remove_failed: boolean
  remove_missing: boolean
  permissions_change: boolean
  import_blocked_loop: number
  wanted_missing_loop: number
  remove_failed_loop: number
  remove_missing_loop: number
  permissions_change_loop: number
  permissions_change_chown: string
  permissions_change_chmod: string
  qBittorrent_URL: string
  qBittorrent_username: string
  qBittorrent_password: string
  qBittorrent_active: boolean
  qBittorrent_API_version: string
  created_at: string
  updated_at: string
}

export interface settingsErrorType {
  _id: string
  radarr_URL: string
  radarr_KEY: string
  radarr_API_version: string
  radarr_active: string
  sonarr_URL: string
  sonarr_KEY: string
  sonarr_API_version: string
  sonarr_active: string
  lidarr_URL: string
  lidarr_KEY: string
  lidarr_API_version: string
  lidarr_active: string
  import_blocked: string
  wanted_missing: string
  remove_failed: string
  remove_missing: string
  permissions_change: string
  import_blocked_loop: string
  wanted_missing_loop: string
  remove_failed_loop: string
  remove_missing_loop: string
  permissions_change_loop: string
  permissions_change_chown: string
  permissions_change_chmod: string
  qBittorrent_URL: string
  qBittorrent_username: string
  qBittorrent_password: string
  qBittorrent_active: string
  qBittorrent_API_version: string
  created_at: string
  updated_at: string
}
