const qBittorrentSchema = `
  type Torrent {
    added_on: Int!
    amount_left: Int!
    auto_tmm: Boolean!
    availability: Float!
    category: String!
    completed: Int!
    completion_on: Int!
    content_path: String!
    dl_limit: Int!
    dlspeed: Int!
    download_path: String!
    downloaded: Int!
    downloaded_session: Int!
    eta: Int!
    f_l_piece_prio: Boolean!
    force_start: Boolean!
    hash: String!
    inactive_seeding_time_limit: Int!
    infohash_v1: String!
    infohash_v2: String!
    last_activity: Int!
    magnet_uri: String!
    max_inactive_seeding_time: Int!
    max_ratio: Float!
    max_seeding_time: Int!
    name: String!
    processedName: String!
    num_complete: Int!
    num_incomplete: Int!
    num_leechs: Int!
    num_seeds: Int!
    priority: Int!
    progress: Float!
    ratio: Float!
    ratio_limit: Float!
    save_path: String!
    seeding_time: Int!
    seeding_time_limit: Int!
    seen_complete: Int!
    seq_dl: Boolean!
    size: Float!
    state: String!
    super_seeding: Boolean!
    tags: String!
    time_active: Int!
    total_size: Float!
    tracker: String!
    trackers_count: Int!
    up_limit: Int!
    uploaded: Int!
    uploaded_session: Int!
    upspeed: Int!
    matchStrings: [String]
    torrentType: String
  }
`
export default qBittorrentSchema
